GameLoop is completed
a8901053/Survive.io pull request #28
Opened 2020-09-05 16:19 UTC by timt1028

GameLoop is completed

2020-09-05 16:34 UTC, snowmancc reviewed
LGTM

2020-09-06 05:35 UTC, Johnny850807 requested changes
Review done.

2020-09-06 05:35 UTC, Johnny850807 commented on client/src/main/java/tw/waterball/survive/io/client/sprite/Weapon/Weapon.java
>      private boolean isInFloor;
rename it to `isOnTheGround` 
according to 冠宇's naming

2020-09-06 05:35 UTC, Johnny850807 commented on client/src/main/java/tw/waterball/survive/io/client/sprite/Weapon/Weapon.java
>      private int heldPlayerId;
`holderId`

2020-09-06 05:38 UTC, Johnny850807 requested changes

2020-09-06 05:38 UTC, Johnny850807 commented on client/src/main/java/tw/waterball/survive/io/client/controller/EventController.java
>  	public void onPlayerLoginSuccess() {
`onPlayerLoginSuccessfully`

grammatically mistake, be careful ;)

2020-09-06 05:38 UTC, Johnny850807 commented on client/src/main/java/tw/waterball/survive/io/client/controller/SpriteContainer.java
> +    public void removeSprites(Sprite sprite) {
`removeSprite`, not plural since you only remove one sprite.

2020-09-06 11:02 UTC, Wally5077 requested changes

2020-09-07 06:21 UTC, Johnny850807 approved these changes
Look good to me

2020-09-07 06:22 UTC, Johnny850807 commented on client/src/main/java/tw/waterball/survive/io/client/view/GameView.java
> +	public void onRender(List<Sprite> sprites) {
好啦你很猛啦

2020-09-07 10:34 UTC, Wally5077 requested changes

2020-09-07 10:34 UTC, Wally5077 commented on client/src/main/java/tw/waterball/survive/io/client/controller/SpriteContainer.java
> +    private List<Sprite> sprites = new ArrayList<>();
我想 sprites 的參考不會變動 , 或許可以在前面加 final

2020-09-07 13:55 UTC, snowmancc approved these changes
LGFM

2020-09-07 13:57 UTC, Wally5077 approved these changes

2020-09-07 13:57 UTC, merged