Implement "WorldObject/Role" part of methods
a8901053/Survive.io pull request #41
Opened 2020-09-11 11:55 UTC by a8901053

# Changes
Implement "WorldObject/Role" turnTo,move,useWeapon and switchCurrentWeapon methods.

# Screenshot (Optional)

2020-09-11 13:11 UTC, Johnny850807 requested changes
Thank you! Review done.

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/WorldObject.java
> +    public WorldObject() {
`WorldObject` can default its location, but its body's size should be explicitly passed from the constructor.
As the following, FYI:
```java
public WorldObject(Dimension size) {
    this.body =  new Rectangle(size);
}
```

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/role/Player.java
> +    private final static int WEAPON_SLOTS_AMOUNT = 2;
`WEAPON_SLOTS_SIZE`

You should keep your naming **consistent**!!!!!!

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/role/Player.java
>  public class Player extends Role implements ClientApi {
```java
/**
 * @author - a89010531111@gmail.com
 */
```

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/role/Role.java
> +        initWeaponSlots();
Great to extract it to another method. 👍

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/role/Role.java
> +    public void turnTo(float angle) {
`turnAngleTo`

We should give it a better name when it comes up to our brain.

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/role/Role.java
> +        hp -= damage;
No `def` involved? You can create another issue for this :).

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/role/Role.java
> +    public void addWeaponToWeaponSlot(Weapon weapon, int weaponSlotIndex) {
rename it to `putWeaponToSlot`

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/role/Role.java
> +    public Weapon getWeaponByWeaponSlotIndex(int weaponSlotIndex) {
`getWeaponBySlotIndex`

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/weapon/Gun.java
> +    public void reload(List<Magazine> magazines) {
Not sure why a list of magazines is passed here? 
Shouldn't the gun only be reloaded with one magazine?

2020-09-11 13:11 UTC, Johnny850807 commented on server/src/test/java/tw/waterball/survive/io/server/worldobject/role/RoleTest.java
> +
No Space.

2020-09-12 20:27 UTC, ShawnSWu reviewed
LGTM

2020-09-13 04:52 UTC, a8901053 commented on api/src/main/java/tw/waterball/survive/io/api/api/ServerApi.java
> +    void turnTo(TurnToRequest turnToRequest);
> Would it be better if it was name turnDirection()?
This is turn angle not direction.

2020-09-13 04:55 UTC, a8901053 commented on server/src/main/java/tw/waterball/survive/io/server/worldobject/weapon/Gun.java
> +    public void reload(List<Magazine> magazines) {
如果傳入單個彈夾，也許會有裝到沒滿的彈夾，所以傳入玩家身上的所有彈夾去遍歷，讓很多彈夾的狀態下裝子彈一定能裝滿

2020-09-13 06:29 UTC, Johnny850807 approved these changes
ＬＧＴＭ

2020-09-13 06:30 UTC, merged