Implement GameLoop to update sprites and call game listener to render at a fixed time.
a8901053/Survive.io pull request #65
Opened 2020-09-17 15:26 UTC by a8901053

# Changes
Implement GameLoop to update sprites and call game listener to render at a fixed time.

# Screenshot (Optional)

2020-09-17 15:50 UTC, Johnny850807 requested changes
Review done

2020-09-17 15:50 UTC, Johnny850807 commented on client/src/main/java/tw/waterball/survive/io/client/view/GameView.java
> +public abstract class GameView implements GameListener {
Put `GameListener` into `GameLoop` as an inner-class, and rename it to `Listener`
so it can be referenced by  `GameLoop.Listener`

2020-09-17 15:50 UTC, Johnny850807 commented on game/src/main/java/tw/waterball/survive/io/game/gameloop/GameListener.java
> +    void onRender(List<Sprite> sprites);
`onUpdate()`
GameLoop's Listener should not be bound to the concept of rendering

2020-09-17 15:50 UTC, Johnny850807 commented on game/src/main/java/tw/waterball/survive/io/game/gameloop/GameLoop.java
> +    private final GameListener gameListener;
We should have multiple listeners, so it should be a `Set<GameListener> gameListeners`

2020-09-17 15:50 UTC, Johnny850807 commented on game/src/main/java/tw/waterball/survive/io/game/gameloop/GameLoop.java
> +                if (gameListener != null) {
and hence, you don't need to check the nullity, since it's a set.

2020-09-17 15:50 UTC, Johnny850807 commented on game/src/main/java/tw/waterball/survive/io/game/gameloop/GameLoop.java
> +    public GameLoop(SpriteContainer spriteContainer, GameListener gameListener) {
No `GameListener` as the parameter, since the listeners will be added by a adder `addListener`

2020-09-17 16:14 UTC, nyngwang approved these changes
LGTM.

2020-09-18 03:04 UTC, Johnny850807 approved these changes
LGTM

2020-09-18 04:13 UTC, ShawnSWu approved these changes
LGTM

2020-09-18 04:14 UTC, merged