JFrame / JPanel canvas implementation
a8901053/Survive.io pull request #74
Opened 2020-09-19 14:41 UTC by timt1028

# Changes
JFrame / JPanel canvas implementation

# Screenshot (Optional)
![view](https://user-images.githubusercontent.com/69762490/93669755-e9bb7080-fac8-11ea-9b9d-3014b20200df.PNG)

2020-09-20 07:01 UTC, Johnny850807 requested changes
Review done.

2020-09-20 07:01 UTC, Johnny850807 commented on client/src/main/java/tw/waterball/survive/io/client/view/StandardGameView.java
> +    private void paintSprite(Graphics g, Sprite sprite) {
put this method below `Canvas` since `Canvas` uses it.

The invokee should be put below the invoker.

2020-09-20 14:19 UTC, Wally5077 approved these changes
LGTM

2020-09-20 14:19 UTC, Wally5077 commented on client/src/main/java/tw/waterball/survive/io/client/view/GameView.java
> +public abstract class GameView extends JFrame implements GameLoop.Listener {
這邊 GameView 為什麼繼承 JFrame？

2020-09-20 14:19 UTC, Wally5077 commented on client/src/main/java/tw/waterball/survive/io/client/view/StandardGameView.java
> +        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
我想這些初始化配置 , 或許可以寫進個方法。

2020-09-22 17:13 UTC, Johnny850807 approved these changes
ＬＧＴＭ

2020-09-22 19:01 UTC, a8901053 approved these changes
LGTM

2020-09-27 16:33 UTC, timt1028 commented on client/src/main/java/tw/waterball/survive/io/client/view/GameView.java
> +public abstract class GameView extends JFrame implements GameLoop.Listener {
在想在這只要繼承是GameView，都會用到JFrame，謝謝。

2020-09-29 13:22 UTC, merged